version: '2'
services:
  input:
    build: .
    links:
      - "rethinkdb:rethinkdb"
      - "elasticsearch:elasticsearch"
    environment:
      - RETHINKDB_HOST=rethinkdb
      - ELASTICSEARCH_HOST=elasticsearch
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
